/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UsecasesRouteImport } from './routes/usecases'
import { Route as SkillBuilderRouteImport } from './routes/skill-builder'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsecasesUsecaseIdRouteImport } from './routes/usecases.$usecaseId'
import { Route as ExecutionMonitorUsecaseIdRouteImport } from './routes/execution-monitor.$usecaseId'
import { Route as UsecasesUsecaseIdExecutionsRouteImport } from './routes/usecases.$usecaseId.executions'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UsecasesRoute = UsecasesRouteImport.update({
  id: '/usecases',
  path: '/usecases',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillBuilderRoute = SkillBuilderRouteImport.update({
  id: '/skill-builder',
  path: '/skill-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsecasesUsecaseIdRoute = UsecasesUsecaseIdRouteImport.update({
  id: '/$usecaseId',
  path: '/$usecaseId',
  getParentRoute: () => UsecasesRoute,
} as any)
const ExecutionMonitorUsecaseIdRoute =
  ExecutionMonitorUsecaseIdRouteImport.update({
    id: '/execution-monitor/$usecaseId',
    path: '/execution-monitor/$usecaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsecasesUsecaseIdExecutionsRoute =
  UsecasesUsecaseIdExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => UsecasesUsecaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/knowledge': typeof KnowledgeRoute
  '/migrations': typeof MigrationsRoute
  '/observability': typeof ObservabilityRoute
  '/skill-builder': typeof SkillBuilderRoute
  '/usecases': typeof UsecasesRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/execution-monitor/$usecaseId': typeof ExecutionMonitorUsecaseIdRoute
  '/usecases/$usecaseId': typeof UsecasesUsecaseIdRouteWithChildren
  '/usecases/$usecaseId/executions': typeof UsecasesUsecaseIdExecutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/knowledge': typeof KnowledgeRoute
  '/migrations': typeof MigrationsRoute
  '/observability': typeof ObservabilityRoute
  '/skill-builder': typeof SkillBuilderRoute
  '/usecases': typeof UsecasesRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/execution-monitor/$usecaseId': typeof ExecutionMonitorUsecaseIdRoute
  '/usecases/$usecaseId': typeof UsecasesUsecaseIdRouteWithChildren
  '/usecases/$usecaseId/executions': typeof UsecasesUsecaseIdExecutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/knowledge': typeof KnowledgeRoute
  '/migrations': typeof MigrationsRoute
  '/observability': typeof ObservabilityRoute
  '/skill-builder': typeof SkillBuilderRoute
  '/usecases': typeof UsecasesRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/execution-monitor/$usecaseId': typeof ExecutionMonitorUsecaseIdRoute
  '/usecases/$usecaseId': typeof UsecasesUsecaseIdRouteWithChildren
  '/usecases/$usecaseId/executions': typeof UsecasesUsecaseIdExecutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluation'
    | '/knowledge'
    | '/migrations'
    | '/observability'
    | '/skill-builder'
    | '/usecases'
    | '/workspace'
    | '/execution-monitor/$usecaseId'
    | '/usecases/$usecaseId'
    | '/usecases/$usecaseId/executions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation'
    | '/knowledge'
    | '/migrations'
    | '/observability'
    | '/skill-builder'
    | '/usecases'
    | '/workspace'
    | '/execution-monitor/$usecaseId'
    | '/usecases/$usecaseId'
    | '/usecases/$usecaseId/executions'
  id:
    | '__root__'
    | '/'
    | '/evaluation'
    | '/knowledge'
    | '/migrations'
    | '/observability'
    | '/skill-builder'
    | '/usecases'
    | '/workspace'
    | '/execution-monitor/$usecaseId'
    | '/usecases/$usecaseId'
    | '/usecases/$usecaseId/executions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationRoute: typeof EvaluationRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MigrationsRoute: typeof MigrationsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SkillBuilderRoute: typeof SkillBuilderRoute
  UsecasesRoute: typeof UsecasesRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
  ExecutionMonitorUsecaseIdRoute: typeof ExecutionMonitorUsecaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usecases': {
      id: '/usecases'
      path: '/usecases'
      fullPath: '/usecases'
      preLoaderRoute: typeof UsecasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-builder': {
      id: '/skill-builder'
      path: '/skill-builder'
      fullPath: '/skill-builder'
      preLoaderRoute: typeof SkillBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usecases/$usecaseId': {
      id: '/usecases/$usecaseId'
      path: '/$usecaseId'
      fullPath: '/usecases/$usecaseId'
      preLoaderRoute: typeof UsecasesUsecaseIdRouteImport
      parentRoute: typeof UsecasesRoute
    }
    '/execution-monitor/$usecaseId': {
      id: '/execution-monitor/$usecaseId'
      path: '/execution-monitor/$usecaseId'
      fullPath: '/execution-monitor/$usecaseId'
      preLoaderRoute: typeof ExecutionMonitorUsecaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usecases/$usecaseId/executions': {
      id: '/usecases/$usecaseId/executions'
      path: '/executions'
      fullPath: '/usecases/$usecaseId/executions'
      preLoaderRoute: typeof UsecasesUsecaseIdExecutionsRouteImport
      parentRoute: typeof UsecasesUsecaseIdRoute
    }
  }
}

interface UsecasesUsecaseIdRouteChildren {
  UsecasesUsecaseIdExecutionsRoute: typeof UsecasesUsecaseIdExecutionsRoute
}

const UsecasesUsecaseIdRouteChildren: UsecasesUsecaseIdRouteChildren = {
  UsecasesUsecaseIdExecutionsRoute: UsecasesUsecaseIdExecutionsRoute,
}

const UsecasesUsecaseIdRouteWithChildren =
  UsecasesUsecaseIdRoute._addFileChildren(UsecasesUsecaseIdRouteChildren)

interface UsecasesRouteChildren {
  UsecasesUsecaseIdRoute: typeof UsecasesUsecaseIdRouteWithChildren
}

const UsecasesRouteChildren: UsecasesRouteChildren = {
  UsecasesUsecaseIdRoute: UsecasesUsecaseIdRouteWithChildren,
}

const UsecasesRouteWithChildren = UsecasesRoute._addFileChildren(
  UsecasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRoute,
  KnowledgeRoute: KnowledgeRoute,
  MigrationsRoute: MigrationsRoute,
  ObservabilityRoute: ObservabilityRoute,
  SkillBuilderRoute: SkillBuilderRoute,
  UsecasesRoute: UsecasesRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
  ExecutionMonitorUsecaseIdRoute: ExecutionMonitorUsecaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
